; Development configuration 

[DB]
dbtype = mysql
dbhost = 127.0.0.1
dbname = my_social_network_base
dbuser = root
dbpassword = root
mysql_path = "C:\PRW2526\tools\xampp\mysql\bin\"
;mysql_path = "/Applications/XAMPP/xamppfiles/bin/"


[Controllers]
default_controller = main

[Web]
web_root = "/Partie-JS/ExercicesIntro/Chap1/Exercice3/"

[Sanitization]
; Certaines informations de l'utilisateur ne doivent pas être sanitizées en entrée mais 
; plutôt en sortie. C'est le cas du texte au format Markdown (voir plus loin). Pour cela, 
; le fichier de configuration contient un tableau insafe_inputs qui reprend le nom des 
; champs qu'il ne faut pas sanitizer en entrée.
;insafe_inputs[] = markdown_body
;insafe_inputs[] = test

[JavaScript]
disable_js = false
; les chemins actifs malgré la désactivation de JS
; Chemins relatifs locaux
;enabled_paths[] = "css/bootstrap-5.3.3-dist/js/bootstrap.min.js"
;enabled_paths[] = "lib/popper.min.js"
;enabled_paths[] = "lib/jquery-3.7.1.min.js"
;enabled_paths[] = "lib/masonry.pkgd.min.js"
; URLs CDN (optionnel)
;enabled_paths[] = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
;enabled_paths[] = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js"