#!/usr/bin/env python3

import webbrowser
from pathlib import Path
import subprocess

# print("Hello world")
# url = "https://www.xbox.com/en-US/play/games/fortnite/BT5P2X999VH2"

url = "https://www.xbox.com/en-US/play/launch/fortnite/BT5P2X999VH2"
# webbrowser.get("chromium").open(url2, 1)

chromiumFile = Path("/usr/bin/chromium")

if not chromiumFile.exists():
    process = subprocess.Popen(
        ["sudo", "pacman", "-Syu", "chromium"], stdout=subprocess.PIPE, text=True
    )
    output, _ = process.communicate()
    print(output)
    # Ouvre l'url sur chromium dans une nouvelle page
    webbrowser.get("chromium").open(url, 1)

else:
    webbrowser.get("chromium").open(url, 1)
